name: Sync Images to Private Registry with Skopeo

on:
  schedule:
    # 每天凌晨 2 点运行
    - cron: '0 2 * * *'
  workflow_dispatch: # 支持手动触发

jobs:
  sync-images:
    runs-on: ubuntu-latest

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. 安装 Skopeo
      - name: Install Skopeo
        run: |
          sudo apt-get update && sudo apt-get install -y skopeo

      # 3. 设置私有仓库认证
      - name: Login to private registry
        env:
          PRIVATE_REGISTRY: ${{ secrets.PRIVATE_REGISTRY_HW }}
          PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY_HW }}
          PRIVATE_REGISTRY_USER: ${{ secrets.PRIVATE_REGISTRY_USER_HW }}
          PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD_HW }}

        run: |
          echo "$PRIVATE_REGISTRY_PASSWORD" | skopeo login --username="$PRIVATE_REGISTRY_USER" --password-stdin "$PRIVATE_REGISTRY"

      # 4. 同步镜像
      - name: Sync images with Skopeo
        run: |
          # 读取 mirror-list.txt 文件中的每一行镜像名称
          while IFS= read -r image; do
            # 删除前后空格
            image=$(echo "$image" | xargs)
            # 跳过空行和注释行
            if [[ -z "$image" || "$image" =~ ^# ]]; then
              continue
            fi
            
            #打印当前执行的镜像
            echo "$image"
            
            # 生成目标镜像名称
            target_image="$PRIVATE_REGISTRY/$PRIVATE_REPOSITORY/$image"
            
            #打印目标镜像名称
            echo "$target_image"
            
            # 使用 Skopeo 复制镜像
            skopeo copy --all "docker://$image" "docker://$target_image"
            echo "Synced $image to $target_image"
          done < mirror-list.txt
