# 定义工作流名称
name: Sync Images to Private Registry with Skopeo

# 定义触发条件
on:
  schedule:
  # 每天凌晨 2 点运行
  - cron: '0 2 * * *'
  push:
    branches:
      - main  # 每次推送至 main 分支时运行
  workflow_dispatch:
    # 支持手动触发

    # 定义环境变量
env:
  PRIVATE_REGISTRY: ${{ secrets.PRIVATE_REGISTRY_HW }}
  PRIVATE_REPOSITORY: ${{ secrets.PRIVATE_REPOSITORY_HW }}
  PRIVATE_REGISTRY_USER: ${{ secrets.PRIVATE_REGISTRY_USER_HW }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.PRIVATE_REGISTRY_PASSWORD_HW }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      batches: ${{ steps.process_mirror_list.outputs.batches }}

    steps:
    # 1. 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3
    # 2. 安装 必要的软件包
    - name: Install Skopeo
      run: |
        sudo apt-get update && \
        sudo apt-get install -y \
                     skopeo \
                     jq \
                     dos2unix

    # 3. 处理 mirror-list.txt 文件
    - name: Process mirror-list.txt
      id: process_mirror_list
      run: |
        # 检查并转换文件编码格式为UTF-8
        iconv -f $(file -bi mirror-list.txt | grep -Po 'charset=\K[^;]+') -t UTF-8 mirror-list.txt -o mirror-list.txt

        # 将文件换行模式转换为Linux LF
        dos2unix mirror-list.txt

        # 删除每一行镜像前后空格，跳过空行及注释行
        awk '{gsub(/^[ \t]+|[ \t]+$/, ""); if ($0 != "" && $0 !~ /^#/) print $0}' mirror-list.txt > processed-mirror-list.txt

        # 读取 processed-mirror-list.txt 文件内容并转换为数组
        mapfile -t images < processed-mirror-list.txt
        echo "Processed images: ${images[@]}"

        # 将镜像列表分割成每批5个
        batch_size=5
        batches=()
        for ((i=0; i<${#images[@]}; i+=batch_size)); do
          batches+=("${images[@]:i:batch_size}")
        done

        # 将批次转换为 JSON 格式并输出
        batches_json=$(printf '%s\n' "${batches[@]}" | jq -R -s -c 'split("\n") | map(select(length > 0))')
        echo "batches=$batches_json" >> $GITHUB_OUTPUT

  sync-images:
    timeout-minutes: 30 # 适当延长超时时间以应对较大镜像同步
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        batch: ${{ fromJson(needs.setup.outputs.batches) }}
        max-parallel: 2 # 限制同时运行的批次数量

    steps:
    # 1. 设置私有仓库认证
    - name: Login to private registry
      run: |
        echo "$PRIVATE_REGISTRY_PASSWORD" | skopeo login --username="$PRIVATE_REGISTRY_USER" --password-stdin "$PRIVATE_REGISTRY"

    # 2. 同步镜像
    - name: Sync images with Skopeo
      run: |
        for image in ${{ join(matrix.batch, ' ') }}; do
          if [[ -n "$image" && ! "$image" =~ ^# ]]; then
            # 删除前后空格
            image=$(echo "$image" | xargs)

            # 生成目标镜像名称
            target_image="$PRIVATE_REGISTRY/$PRIVATE_REPOSITORY/$(basename "$image")"

            # 使用 Skopeo 复制镜像
            skopeo copy -a \
            --retry-times 3 \          # 添加重试机制
            --command-timeout 300s \   # 设置单次操作超时时间
            --insecure-policy \
            --src-tls-verify=false \
            --dest-tls-verify=false \
            "docker://$image" \
            "docker://$target_image"
            echo "Synced $image to $target_image"
          fi
        done